services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: humanslovedbs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgresdb
      ADMINER_DEFAULT_DRIVER: pgsql

  backend:
    environment:
      POSTGRES_SERVER: postgresdb
      POSTGRES_PASSWORD: humanslovedbs
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb
    restart: always

  frontend:
    environment:
      VITE_API_URL: "https://devopstask2.osinachi.me"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always

  nginxproxymananger:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '8090:81' # Admin Web Port

    environment:
      DB_SQLITE_FILE: "/opt/nginxproxymananger/db.sqlite" # Path to SQLite file

    volumes:
      - /opt/nginxproxymananger:/opt/nginxproxymananger # Mount directory containing db.sqlite
      - /opt/nginxproxymananger/letsencrypt:/etc/letsencrypt # Mount letsencrypt directory for SSL certificates
      - ./init_nginxproxymanager.sh:/init_nginxproxymanager.sh # Mount the initialization script

    entrypoint: [ "/bin/sh", "-c", "/init_nginxproxymanager.sh /init" ]

volumes:
  postgres_data:
